"use strict";
module.exports = {
  config: {
    updateChannel: "stable",
    fontSize: 14,
    fontFamily:
      '"JetBrainsMono Nerd Font", "JetBrains Mono", "DejaVu Sans Mono", Consolas, monospace',
    fontWeight: "normal",
    fontWeightBold: "bold",
    lineHeight: 1.2,
    letterSpacing: 0,
    cursorColor: "#ff4fcf",
    cursorAccentColor: "#1a1b26",
    cursorShape: "BLOCK",
    cursorBlink: true,
    foregroundColor: "#c0caf5",
    backgroundColor: "#1a1b26",
    selectionColor: "rgba(255,79,207,0.2)",
    borderColor: "#24283b",
    css: "",
    termCSS: "",
    workingDirectory: "",
    showHamburgerMenu: "",
    showWindowControls: "",
    padding: "12px 14px",
    colors: {
      black:        "#15161e",
      red:          "#f7768e",
      green:        "#9ece6a",
      yellow:       "#e0af68",
      blue:         "#7aa2f7",
      magenta:      "#bb9af7",
      cyan:         "#7dcfff",
      white:        "#a9b1d6",
      lightBlack:   "#414868",
      lightRed:     "#f7768e",
      lightGreen:   "#9ece6a",
      lightYellow:  "#e0af68",
      lightBlue:    "#7aa2f7",
      lightMagenta: "#bb9af7",
      lightCyan:    "#7dcfff",
      lightWhite:   "#c0caf5",
    },
    shell: "",
    shellArgs: ["--login"],
    env: {},
    bell: false,
    copyOnSelect: true,
    defaultSSHApp: true,
    quickEdit: false,
    macOptionSelectionMode: "vertical",
    webGLRenderer: true,
    webLinksActivationKey: "",
    disableLigatures: false,
    disableAutoUpdates: false,
    screenReaderMode: false,
    preserveCWD: true,
  },
  plugins: ["hyper-tab-icons-plus", "hyper-search"],
  localPlugins: [],
  keymaps: {
    "tab:new":            "cmd+t",
    "tab:next":           "cmd+shift+]",
    "tab:prev":           "cmd+shift+[",
    "pane:splitRight":    "cmd+d",
    "pane:splitDown":     "cmd+shift+d",
    "pane:next":          "cmd+]",
    "pane:prev":          "cmd+[",
    "editor:clearBuffer": "cmd+k",
  },
};
